# definition file for all available AIs
# there are only 17 total possible, so don't try to add any more
#
# engines: (minimum, maximum, default)
#     AlphaBeta   (3, 6, 5)
#     MiniMax     (1, 4, 3)
#     MiniMax++   (2, 5, 4)
#     NegaScout   (3, 6, 5) (default)
#     Random      (1, 1, 1)
# added a few comments for an idea for relative difficulty
#
# "funName" is the displayed name in-Game
#   can also be used by a player to invite this AI to their game
#   if you want more of one type available, funName can be comma-delimited to add more AI
# e.g. funName: "Bob, George, Moe" gives 3 AI of that type
# !! Names CANNOT be repeated, or only the last of that name will be available !!
# if funName is null, will be the definition node (e.g. ai01)
#
# "comment" is an optional comment which will be shown to players if they list the AI's
#
# "payout_multiplier" applies if Economy support is enabled.  Default is 1.0 - it could be
#   raised for tougher engines and lowered for weaker engines.

AI:
  ai01:
    # decent engine.. not to be underestimated, even at this low depth
    funName:
    engine: "AlphaBeta"
    depth: 3
    enabled: true
    comment: Decent. Don't underestimate.
  ai02:
    funName:
    engine: "AlphaBeta"
    depth: 4
    enabled: true
  ai03:
    funName:
    engine: "AlphaBeta"
    depth: 5
    enabled: true
  ai04:
    funName:
    engine: "AlphaBeta"
    depth: 6
    enabled: true
  ai05:
    #this depth is quite easy
    funName:
    engine: "MiniMax"
    depth: 1
    enabled: true
    comment: Not too tough.
  ai06:
    funName:
    engine: "MiniMax"
    depth: 2
    enabled: true
  ai07:
    # fair competitor, but sometimes confused (if has the upper-hand)
    funName:
    engine: "MiniMax"
    depth: 3
    enabled: true
    comment: Fair, but sometimes get confused.
  ai08:
    funName:
    engine: "MiniMax"
    depth: 4
    enabled: true
  ai09:
    funName:
    engine: "MiniMax++"
    depth: 2
    enabled: true
  ai10:
    #improved over ai07
    funName:
    engine: "MiniMax++"
    depth: 3
    enabled: true
  ai11:
    funName:
    engine: "MiniMax++"
    depth: 4
    enabled: true
  ai12:
    funName:
    engine: "MiniMax++"
    depth: 5
    enabled: true
  ai13:
    # good, but sometimes confused (if has the upper-hand)
    # once could've had a 1-move mate that it instead waited another 6 moves
    funName:
    engine: "NegaScout"
    depth: 3
    enabled: true
    comment: Good, but sometimes get confused.
  ai14:
    funName:
    engine: "NegaScout"
    depth: 4
    enabled: true
  ai15:
    # quite good
    funName:
    engine: "NegaScout"
    depth: 5
    enabled: true
  ai16:
    funName:
    engine: "NegaScout"
    depth: 6
    enabled: true
  ai17:
    # idiotic..
    # probably shouldn't be allowed to play against such stupidity
    funName:
    engine: "Random"
    depth: 1
    enabled: true
    payout_multiplier: 0.1
    comment: Completely stupid.
