name: ChessCraft
main: me.desht.chesscraft.ChessCraft
version: 0.2
softdepend: [ Permissions ]
commands:
  chess:
    description: Play Chess
    usage: |
      /chess create board <name> [-style <style>]
      /chess create game [<gamename>] [<boardname>]
      /chess delete (board|game) <name>
      /chess list (board|game> [<name>]
      /chess play [<gamename>]
      /chess invite <playername>
      /chess join
      /chess start
      /chess move <move>
      /chess resign
      /chess offer (draw|swap)
      /chess yes
      /chess no
      /chess tp [<gamename>]
      /chess redraw
      /chess save
      /chess reload
      /chess page <page-number>
      /chess setcfg <item> <value>
      /chess getcfg [<item>]
